config/routes.rb
Rails.application.routes.draw do

  root 'projects#index', as: 'index'

  resources :projects do
    resources :tasks
  end

  post 'tasks/complete_task' => 'tasks#complete_task'

  post 'tasks/update_positions' => 'tasks#update_positions'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy
  accepts_nested_attributes_for :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  acts_as_list scope: :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, task_attributes: [:title])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project, except: [:complete_task, :update_positions]
  before_action :set_task, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @project, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @project, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete_task
    task = Task.find(params[:task_id])
    task.completed = !task.completed
    if task.save
      render status: 200, json: {
            success: true,
            completed: task.completed
      }.to_json
    end
  end

  def update_positions
    if params[:position] == 'down'
      Task.find(params[:current_row]).increment_position
    else
      Task.find(params[:current_row]).decrement_position
    end
    render status: 200, json: {
            success: true,
      }.to_json
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :due_date, :description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskman</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4.3.2/css/metro-all.min.css">

  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <div class="form-group">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table class="table bordered">
  <thead>
    <tr>
      <th>Project name</td>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td>
          <%= link_to project.name, project %>

          <%= link_to edit_project_path(project) do %>
              <span class="mif-pencil fg-green"></span>
          <% end %>
          <%= link_to  project, method: :delete, remote: true, data: { confirm: 'Are you sure?' } do %>
              <span class="mif-bin fg-red"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>
  <%= link_to projects_path do %>
      <span class="mif-arrow-left fg-blue"></span>
  <% end %>

  <%= @project.name %>

  <%= link_to edit_project_path(@project) do %>
      <span class="mif-pencil fg-green"></span>
  <% end %>

  <span class="mif-bin fg-red"></span>
  </h1>


</p>


<%= form_for(@project, :html=>{:class => "inline-form", :id=>"new_task",:multipart => true,:remote=>true}) do |f |%>
  <%= f.fields_for :task do |t| %>
    <%= t.text_field :title, :placeholder => "Enter task title", :class => "metro-input" %>
    <%= t.submit "Create task" %>
  <% end %>
<% end %>

<table class="table row-hover row-border">
  <thead>
    <tr>
      <th>Completed</th>
      <th>Title</th>
      <th>Due date</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @project.tasks.each do |task| %>
      <tr id="row_<%= task.id %>" <%= 'class=completed' if task.completed %> data-rowid="<%= task.id %>" data-position="<%= task.position %>">
        <td><input class="j-completed" type="checkbox" <%= 'checked' if task.completed %> data-role="checkbox" data-task="<%= task.id %>"></td>
        <td><%= task.title %></td>
        <td><%= task.due_date.strftime('%d.%m.%Y') %></td>
        <td><%= task.description %></td>
        <td>
          <%= link_to [@project, task] do %>
              <span class="mif-eye fg-blue"></span>
          <% end %>
          <%= link_to edit_project_task_path(@project, task) do %>
              <span class="mif-pencil fg-green"></span>
          <% end %>
          <%= link_to [@project, task], method: :delete, remote: true, data: { confirm: 'Are you sure?' } do %>
              <span class="mif-bin fg-red"></span>
          <% end %>

          <span class="j-up mif-chevron-thin-up fg-blue"></span>
          <span class="j-down mif-chevron-thin-down fg-blue"></span>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Task', new_project_task_path(@project) %>

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.text_field :due_date, "data-role" => "calendarpicker" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <% if @task.persisted? %>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @project.tasks %>


<%= link_to 'Back', @project %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', @project %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_task_path(@project.task) %> |
<%= link_to 'Back', project_path %>